apiVersion: v1
kind: Secret
metadata:
    name: yvoke-postgres-superuser
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bN9d+e6zuQQ=,iv:GVHuqXVed0tv+dDNQhhMIPyZuSZEIXW6MswCEwg3vcc=,tag:P3/lV/YwwJV3UXof+P50ng==,type:str]
    password: ENC[AES256_GCM,data:daICGZ6XA3t2Kpg9GC9CIVD5ko/u/fa8zgUAhkHqFEddrQ==,iv:1MO57BPneubgLWBCijH5dqplN5ZVYIpezCwcu5IgzRc=,tag:3jhcWT5654SDfxIxo3quoA==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MXVSbzZGWFJGQmJDUE9v
            a3krdWgxVDdiMCtUL2IzYWg4aUZyMVppQTBJClE4VHVhaDZqcXNhZEpOODdseS9T
            ajBwOUVSZzUrUzlFcVJ1c3FycXpRUGsKLS0tIFdPZldWdmRHWWpWdmZ0bldsM2t2
            TVhGSEdKa3BLTFAxbWwzTC9CdStHejAKxtqxWskKzjwVBEmpJebJWKfbRH+tuA28
            ifod9miWQplB/3RhYZ0TEsNLxEjj0LLs3CvrLPHgHxqzXVrtKz67sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T19:51:11Z"
    mac: ENC[AES256_GCM,data:9F91F675rzEmRTd3TcMoz3czEmkx7SYt5qUiL801NL9hceqj2Dn3sYXfEnUNRxrqKBDwMQUYv49UhMAHP0WSj7t6HDTCVxrDOItcsCZir7EOcjgi92EZAblOH2X8o+90GfihwLWvc5BKWRuyd9dafG1jCEm6mpvTbjks+S1NY5I=,iv:YqQQpOrCoGNfPOslZujWsL2f6QqTLuj1n83JE70XtXA=,tag:zW9bxpu1MmGDpMTquVJ/9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
