apiVersion: v1
kind: Secret
metadata:
    name: yvoke-postgres-auth
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:jDjb1rMvx6M=,iv:Zh1cxlwAzTnG/jmGwR48KpQbACRPkyDPYCL8/EOoNgs=,tag:0SCASE91andM00qKoC1rug==,type:str]
    password: ENC[AES256_GCM,data:K3pvoVRTyLw5UPUFT/z65JgLGUfhkZFFqBxIDrQnsg==,iv:q+EExTGK3UmMjfKUVhaX6cFxF5FFaSpiOBcc5kI6RCk=,tag:hdtu+bQYMknCIlAPPRC4yA==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNmtPZWZkY2JMQnJnVTl5
            bzhWbHhUaWFrbndtV2hkZEEwcFZ6dU1Vd1Y4CnJmMHhIQ1UzRmxPcnZ5a2o3eXRJ
            TUZCL0lQbFZXY3RsR3RmTlVqb0g2THMKLS0tIDBJRFRqcmQybTBBSy9LU0p4SVBj
            TjRYUHlMQURQLzgxNVVpVG04MlJkb2sKElaIsV6ADE6veezYSZ0VPwe4QaBo5PVI
            2rt0Tuve5M/x6+JE0rzBMvXb5o0sExxVU20U5n/c6cqAjybibgJ5ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T19:51:00Z"
    mac: ENC[AES256_GCM,data:cqo+3SHyPgZXJP0spZ2kZc/bl+MFo2lzt6nXp9uvemaYtTCcSIXOvFJibWAX2XpBSZH9WLcwn1qcO9+LZD2EMb9SWhn1J3vqlFvbObGskoxpekrg4++pVfeTSuVG1bDwhBVvKszQv7ukh3Pck7iN/+acgcHnLiqwQy/VgLXBeC8=,iv:61ZIcVQAFA61u7Hso9Nj0CauKwG04N1lfpnVIeeB15E=,tag:cJ5ADAlws1Y+rGeqiL1AAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
