apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database
  - yvoke-app

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: yvoke
      app.kubernetes.io/environment: k3s

images:
  - name: yvoke/app
    newName: edipal/yvoke-app
    newTag: "latest"
  - name: yvoke/db-migration
    newName: edipal/yvoke-db-migration
    newTag: "latest"
