apiVersion: v1
kind: Secret
metadata:
    name: yvoke-app-secrets
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:WrKBwzqhtl3SMlbuoY0+nNLHVwJFN3YF/auBVSLn5HmYAijnESkY5EvL67sEtucGdvyUSO4=,iv:/G5rPCrXn7k5YRp+Rm0NP4uT6TDExu3HKd6Z1gFw7yY=,tag:sNeZikzQ0+tYQ70TT1rRkw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:QqdJMdmbkZ12nvR9K14VYNAa4+f3ikV5gOIs4kcXdTr8S//TOnDfGXgzv8hPrM+/0Lh/Ybo=,iv:e68XOM+6o9CGM6SGj8VRCry/1sbMMzTtETfLpCIiUuw=,tag:DuY7fPxNNh/rB6HLezIFbg==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:7N7dzxoRqdnenWthq3UHF4/gLi5YcVftn7mlEZpjzETCTR1XuXSCL+DAZugcrycPkKQlXhc=,iv:RXO7fiKNWqIWyQSdC1fSUFOn44hHiifLrTFCyC0A13w=,tag:q2/adLi6ME7zAwAbOO05Uw==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:P4yxd3eIaKkIGfkbO6SYeOfEI/TX9NS1IjsjAMzIe0V/TGFPB0a4sU1Lj7D1zg==,iv:MLC183QKSY6xn4yt0B6J7SK39mGUMaYcfkV1bv7YhC4=,tag:otpjcms9r+Ie8Htj5kntKg==,type:str]
    APP_SECURITY_API_KEY: ENC[AES256_GCM,data:SsZzAqzbG2r9azm57e+tfvDRdAzsRYi2u5JaUgVSBzBuXMchUA5q9Q5MnurlYbNKmPbtXKFhkV0bMEmjCiMCew==,iv:+mol7sdBR35kgHxCGkX3U6HQETlUeJUkZNIHkxUrsQ8=,tag:NzhNG/2O/aUAPBowewSAJQ==,type:str]
    ENTRA_CLIENT_SECRET: ENC[AES256_GCM,data:im3ggp+Kxzr0osh1TJZ2rshmEcczZnQH1bGhXFnb5h2+zOfiRFPA4Q==,iv:a53dOPsl2vk1ZWsCL8+69ijF5cP9SvVsfQTksUxwKdA=,tag:lDsyE2Q5Kk2lc6zVY1kwQQ==,type:str]
    APP_SECRET_KEY: ENC[AES256_GCM,data:pM41p/W9bdH3G14lkH9O/i81Ff+pW22RfUH/SxVSZt92ycFOvvZJ7crE4O4nAmW7wKrKx2iQmTCmFTMAJZtCAw==,iv:zz4I5MnM873sqgtcYHCgy1kbwj5jZsOFDNjUT+1mnzM=,tag:SZYIIaX7p3VbDbcQhc6jVg==,type:str]
    APP_SECRET_SALT: ENC[AES256_GCM,data:4ak4spqrrOfgTqAiOEgbdgfs8AZZ585HNQt/gCSTXyFGRARx3p8Fq280cqbxKUVETmFHveiqNCxE88Z5xI/SJw==,iv:Cy+27vaS966257gKpceCEwZsI5E0z6r8+NdgaPbeYPU=,tag:FH3po0hLQgZbYLUNlyYaAQ==,type:str]
    CLOUDFLARE_GATEWAY_TOKEN: ENC[AES256_GCM,data:eJmV5pdB6hIxS3odVf+MmbbQOfnKDH9L+je5l69XK2A+efI5bEa1L9hnJKMXlVvRfI9QnzA=,iv:kA5x1Ver/xlu3++24z/0xOQ0T+w/Lr4Z8VYamFG35yI=,tag:w2qQfC8LJ4BrjIFg/mluUQ==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQzNiVW9RZXEwOGtSVDMy
            UmlqcWtFcDJ5YlhRUWs5VG50OThVK0NhMHdZCi9jQUE4cS8ya1dXRUdRbG00L0pi
            eWlXeVRteXByN0s0bzZ6UkFIcVdnblUKLS0tIG1ON0o1OTF6QS9pVlErWXpmRU1i
            RW1oRlU2ZVpaV1BXU3ZEZ0EvL0FqcmcKgv5eK5S92K77RSu1pUV8/+dFTKdzJUww
            PD9DW5cyjlFcQ9jzV+Tancj7KAcgdpzZtdVFVBNW8gmWWM/noJYptw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T19:07:53Z"
    mac: ENC[AES256_GCM,data:Y+CIuk1IQ21+56BXJsPzqYxmlRll524wcVhTMP/o/sn88nsK69v0oMG8OlJChch9RWD8stnl/15Jsofw2AebdIN10sXeTxKLCLcTTdNhg562QJi9hvpSgziEB+JVLG4e5C/cVlHT/26M7ZFPWJzu6EjIKLpDDMV0B57cd1R8yWs=,iv:nR6YIZygDBrPza8Sz+j1SBk41+Ng4//YQTlHnEsn+40=,tag:7RhVnVwuWId5ZiCXbNBFCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
