apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: yvoke-database-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/yvoke-postgres-auth.sops.yaml
  - secrets/yvoke-postgres-superuser.sops.yaml
  - secrets/yvoke-postgres-backup.sops.yaml
