apiVersion: v1
kind: Service
metadata:
  name: yvoke-app
  labels:
    app.kubernetes.io/name: yvoke-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yvoke-app
  ports:
    - name: http
      port: 8080
      targetPort: http
